apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  namespace: banking
spec:
  type: NodePort
  selector:
    app: ledger-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30011
