apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
        chaos: "true"
      annotations:
        chaos-mesh.org/inject: "enabled"
    spec:
      containers:
        - name: ledger-service
          image: ledger-service-local-3
          env:
            - name: POSTGRES_DSN
              value: postgres://postgres:postgres@postgres:5432/transactions?sslmode=disable
            - name: KAFKA_BROKER
              value: host.docker.internal:9092
