apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: banking
spec:
  type: NodePort
  selector:
    app: transaction-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30010 
